version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  app:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - redis
    volumes:
      - ./redis_data:/app/redis_data
      - ./.env:/app/.env
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env

volumes:
  redis_data:

